In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
type(a)   #numpy.ndarray
a.dtype   #dtype('int32')

dtype('int32')

In [ ]:
a.ndim    # 1
a.size    # 3
a.shape   # (3,)

In [12]:
c = np.array([[1,2,3], [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

bool_         Boolean (true or false) stored as a byte
int_          Default integer type (same as C long; normally either int64 or int32)
intc          Identical to C int (normally int32 or int64)
intp          Integer used for indexing (same as C size_t; normally either int32 or int64)
int8          Byte (–128 to 127)
int16         Integer (–32768 to 32767)
int32         Integer (–2147483648 to 2147483647)
int64         Integer (–9223372036854775808 to 9223372036854775807)
uint8         Unsigned integer (0 to 255)
uint16        Unsigned integer (0 to 65535)
uint32        Unsigned integer (0 to 4294967295)
uint64        Unsigned integer (0 to 18446744073709551615)
float_        Shorthand for float64
float16       Half precision float: sign bit, 5-bit exponent, 10-bit mantissa
float32       Single precision float: sign bit, 8-bit exponent, 23-bit mantissa
float64       Double precision float: sign bit, 11-bit exponent, 52-bit mantissa
complex_      Shorthand for complex128
complex64     Complex number, represented by two 32-bit floats (real and imaginary components)
complex128    Complex number, represented by two 64-bit floats (real and imaginary components)

In [13]:
# array with complex numberes
f = np.array([[1,2,3], [4,5,6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [14]:
# full array of Zeroes
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# full array of Ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [21]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [23]:
np.random.random(4)

array([0.86872503, 0.6843008 , 0.23536753, 0.66732669])

In [24]:
np.random.random((3,4))

array([[0.7122067 , 0.28313435, 0.72344422, 0.53294308],
       [0.73374117, 0.7576908 , 0.24129913, 0.16274657],
       [0.70459831, 0.72850323, 0.54176543, 0.79335969]])

In [26]:
A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))
A*B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [28]:
#The result at each position is the sum of the products of each element of
#the corresponding row of the first matrix with the corresponding element 
#of the corresponding column of the second matrix.
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [29]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [30]:
A[1,2]

5

In [36]:
a = np.arange(0,5)
for i in a:
    print(i)

0
1
2
3
4


In [37]:
for row in A:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [45]:
A = np.arange(10, 19).reshape((3, 3))
def foo(x):
    return x/2
np.apply_along_axis(foo, axis=0, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [48]:
A = np.random.random((4,4))
A < 0.5

array([[ True,  True,  True, False],
       [False,  True, False,  True],
       [ True, False,  True,  True],
       [ True, False,  True, False]])